<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rethink_smart_tool_plate">
  <xacro:macro name="rethink_smart_tool_plate" params="side gazebo">
    <xacro:property name="gripper_side" value="${side}" scope="local"/>
    <xacro:property name="rethink_smart_tool_plate_length" value="0.033" scope="global"/>

    <!-- Smart Tool Plate Base Joint -->
    <xacro:property name="end_of_arm_offset" value="-0.005" scope="local"/>
    <joint name="${side}_gripper_base_joint" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 ${end_of_arm_offset}"/>
      <parent link="${side}_hand"/>
      <child link="${side}_smart_tool_plate_base"/>
    </joint>

    <link name="${side}_smart_tool_plate_base">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.2" />
        <inertia ixx="6.9922E-05"  ixy="6.1026E-08"  ixz="-1.7042E-06"
                 iyy="6.8188E-05"  iyz="-1.6118E-08" izz="0.00012392" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://intera_tools_description/meshes/smart_tool_plate/smart_tool_plate.DAE" />
        </geometry>
        <material name="black">
          <color rgba="0.05 0.05 0.05 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${rethink_smart_tool_plate_length/2.0}" rpy="0 0 0" />
          <geometry>
            <cylinder length="${rethink_smart_tool_plate_length}" radius="0.04"/>
          </geometry>
      </collision>
      <collision>
        <origin xyz="0.05 0 ${rethink_smart_tool_plate_length/2.0}" rpy="0 0 0" />
          <geometry>
            <box size="0.04 0.06 ${rethink_smart_tool_plate_length}"/>
          </geometry>
      </collision>
    </link>
    <xacro:if value="${gazebo}">
      <gazebo reference="${side}_smart_tool_plate_base">
        <material>Gazebo/FlatBlack</material>
      </gazebo>
    </xacro:if>

    <joint name="${side}_smart_tool_plate_mount_joint" type="fixed">
      <origin xyz="0 0 ${rethink_smart_tool_plate_length}" rpy="0 0 0" />
      <parent link="${side}_smart_tool_plate_base"  />
      <child  link="${side}_smart_tool_plate_mount" />
    </joint>

    <link name="${side}_smart_tool_plate_mount" />

  </xacro:macro>
</robot>
